homepage/urls.py
from django.urls import path
from .views import homepage
from .views import riwayat
from .views import hobi
from .views import pengalaman
from .views import karya
from .views import contact
from .views import matkulpage
from .views import hapusmatkul
from .views import kegiatan
from .views import prestasi
from .views import caribuku
from .views import data
from .views import login_view
from .views import register
from .views import logout_view
app_name = 'homepage'

urlpatterns = [
    path('', homepage, name='homepage'),
    path('riwayatpendidikan/', riwayat, name='riwayat'),
    path('hobi/', hobi, name='hobi'),
    path('pengalaman/', pengalaman, name="pengalaman"),
    path('karya/', karya, name="karya"),
    path('contact/', contact, name="contact"),
    path('matkulpage/', matkulpage, name='matkulpage'),
    path('<int:pk>', hapusmatkul, name='delete'),
    path('kegiatan/', kegiatan, name='kegiatan'),
    path('prestasi/', prestasi, name='prestasi'),
    path('caribuku/', caribuku, name='caribuku'),
    path('caribuku/data', data, name='data'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register, name='register')

]

story4/urls.py
from django.urls import path, include
from django.contrib import admin
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
     path('', TemplateView.as_view(template_name='register.html'), name='register'),
]

homepage/models.py
from django.db import models

# Create your models here.
class Matkul(models.Model):
    mata_kuliah = models.CharField(max_length=50,default='')
    dosen = models.CharField(max_length=100,default='')
    sks = models.IntegerField()
    tahun = models.IntegerField()
    kelas = models.CharField(max_length=50,default='')

class Forms1 (models.Model):
    Nama = models.CharField(max_length=50, default='')

class Forms2 (models.Model):
    Nama = models.CharField(max_length=50, default='')

class Forms3 (models.Model):
    Nama = models.CharField(max_length=50, default='')

homepage/forms.py
from django import forms
from .models import Forms1, Forms2, Forms3
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class matkulForm(forms.Form):

    mata_kuliah = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Mata Kuliah',
        'type' : 'text',
        'required': True,
    }))

    dosen = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder' : 'Nama Dosen',
        'type' : 'text',
        'required': True,
    }))

    sks = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'placeholder':'Jumlah SKS',
        'type':'number',
    }))


    tahun = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'type' : 'number',
        'placeholder': 'Tahun',
        'required': True,
    }))

    kelas = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type' : 'text',
        'placeholder': 'Kelas',
        'required': True,
    }))

class Forms_band(forms.ModelForm):
    class Meta:
        model = Forms1
        fields = ['Nama']
        

class Forms_nongkrong(forms.ModelForm):
    class Meta:
        model = Forms2
        fields = ['Nama']

class Forms_mabar(forms.ModelForm):
    class Meta:
        model = Forms3
        fields = ['Nama']

class loginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type' : 'text',
        'placeholder': "Enter your username",
        'required': True,
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'type' : 'password',
        'placeholder': "Enter your password",
        'required': True,
    }))


class registerForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username', 'email', 'password1','password2',
        ]
    

homepage/views.py
from django.shortcuts import render, redirect
from .models import Matkul, Forms1, Forms2, Forms3
from .forms import matkulForm, Forms_band, Forms_mabar, Forms_nongkrong, loginForm, registerForm
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
import json
import requests

# Create your views here.
def homepage(request):
    return render(request, 'Homepage.html')

def riwayat(request):
    return render(request, 'RiwayatPendidikan.html')

def hobi(request):
    return render(request, 'Hobi.html')

def pengalaman(request):
    return render(request, 'Pengalaman.html')

def karya(request):
    return render(request, 'Karya.html')

def contact(request):
    return render(request, 'Contact.html')

def matkulpage(request):
    if request.method == "POST":
        form = matkulForm(request.POST)
        if form.is_valid():
            formkuliah = Matkul()
            formkuliah.mata_kuliah = form.cleaned_data['mata_kuliah']
            formkuliah.dosen = form.cleaned_data['dosen']
            formkuliah.sks = form.cleaned_data['sks']
            formkuliah.tahun = form.cleaned_data['tahun']
            formkuliah.kelas = form.cleaned_data['kelas']
            formkuliah.save()
            
        return redirect('/matkulpage')
    else:
        matakuliah = Matkul.objects.all()
        form = matkulForm()
        response = {"matakuliah":matakuliah, 'form' : form}
        return render(request,'Matakuliah.html',response)
    
def hapusmatkul(request,pk):
    if request.method == 'POST':
        Matkul.objects.filter(pk=pk).delete()
        matakuliah = Matkul.objects.all()
        form = matkulForm() 
        form = matkulForm(request.POST)
        if form.is_valid():
            formkuliah = Matkul()
            formkuliah.mata_kuliah = form.cleaned_data['mata_kuliah']
            formkuliah.dosen = form.cleaned_data['dosen']
            formkuliah.sks = form.cleaned_data['sks']
            formkuliah.tahun = form.cleaned_data['tahun']
            formkuliah.kelas = form.cleaned_data['kelas']
            formkuliah.save()
        return redirect('/matkulpage')
    else:
        return redirect('/matkulpage')

def kegiatan(request):
    if request.method == 'POST' and 'btn_form_band' in request.POST:
        forms_band = Forms_band(request.POST)
        if forms_band.is_valid():
            forms_band.save()
    elif request.method == 'POST' and 'btn_form_nongkrong' in request.POST:
        forms_nongkrong = Forms_nongkrong(request.POST)
        if forms_nongkrong.is_valid():
            forms_nongkrong.save()
    elif request.method == 'POST' and 'btn_form_mabar' in request.POST:
        forms_mabar = Forms_mabar(request.POST)
        if forms_mabar.is_valid():
            forms_mabar.save()
    
    forms_band = Forms_band()
    forms_nongkrong = Forms_nongkrong()
    forms_mabar = Forms_mabar()
    peserta_band = Forms1.objects.all()
    peserta_nongkrong = Forms2.objects.all()
    peserta_mabar = Forms3.objects.all()
    context = {
        'list_peserta_band':peserta_band,
        'list_peserta_nongkrong':peserta_nongkrong,
        'list_peserta_mabar':peserta_mabar,
        'forms_band':forms_band,
        'forms_nongkrong':forms_nongkrong,
        'forms_mabar':forms_mabar,
        }
    return render(request, 'Kegiatan.html', context)

def prestasi(request):
    return render(request, 'Prestasi.html')

def caribuku(request):
    response = {}
    return render(request,'Search.html',response)

def data(request):
    try:
        tes = request.GET['q']
    except:
        tes = "a"
    
    json_read = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + tes).json()

    return JsonResponse(json_read)

def login_view(request):
    form = loginForm()
    flag = False
    if request.method == "POST":
        form = loginForm(request.POST)
        if form.is_valid():
            uname = form.cleaned_data['username']
            passw = form.cleaned_data['password']
            user = authenticate(request, username=uname, password = passw)
            if user is not None:
                login(request, user)
                flag = True
                response = {'form':form,'user':user,'flag':flag}
                return redirect('/login')
            else:
                response = {'form':form,'user':user,'flag':flag}
                return redirect('/login')
    else:
        response = {'form':form,'flag':flag}
        return render(request,'login.html',response)

def register(request):
    if request.user.is_authenticated:
	    return redirect ('/register')
    else:
        form = registerForm()
        if request.method == 'POST':
            form = registerForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user)

                return redirect('/login')
			

        context = {'form':form}
        return render(request, 'register.html', context)

def logout_view(request):
    logout(request)
    form = loginForm()
    response = {'form':form}
    return redirect('/login')

homepage/templates/Contact.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
      <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <title>
            Hubungi Dafiq
        </title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:black;">
            <a class="navbar-brand" href="#">Dafiq Achmad - 1906308343</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'homepage:homepage' %}">Halaman Utama</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'homepage:riwayat' %}">Pendidikan</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'homepage:hobi' %}">Hobi & Ketertarikan</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:pengalaman' %}">Pengalaman</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:karya' %}">Karya</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'homepage:contact' %}">Hubungi Saya<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'homepage:matkulpage' %}">Form Jadwal Kuliah</a>
                </li>
                <li class="nav item">
                  <a class="nav-link" href="{% url 'homepage:kegiatan' %}">Form Kegiatan</a>
                </li>
                <li class="nav item">
                  <a class="nav-link" href="{% url 'homepage:prestasi' %}">Prestasi & Kepanitiaan</a>
                </li>
                <li class="nav item">
                  <a class="nav-link" href="{% url 'homepage:caribuku' %}">Cari Buku</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="https://dafiq.herokuapp.com/">Story 1</a>
                </li>
              </ul>
            </div>
          </nav>
          <div class="container">
              <div class="row">
                  <div class="col-md-12">
                    <h1 style="text-align: center; margin-top: 50px; margin-bottom: 50px;">Hubungi Saya</h1><br /><br />
                  </div>
              </div>
              <div class="row">
                      <div class="col-md-4">
                      <a href="https://instagram.com/dafiqachmad"><img src="{% static 'instagram.png' %}" width="300" height="300" style="margin: 0 20px;margin-bottom: 20px;"></a>
                      <p style="font-size: 24px;">@dafiqachmad</p>
                      </div>
                      <div class="col-md-4">
                      <a href="https://twitter.com/dapxq"><img src="{% static 'twitter.png' %}" width="300" height="300" style="margin: 0 20px;margin-bottom: 20px;"></a>
                      <p style="font-size: 24px;">@dapxq</p>
                      </div>
                      <div class="col-md-4">
                      <a href="https://wa.me/6281212833924"><img src="{% static 'whatsapp.png' %}" width="300" height="300" style="margin: 0 20px;margin-bottom: 20px;"></a>
                      <p style="font-size: 24px;">+6281212833924</p>
                      </div>
              </div>
                <div class="row">
                  <div class="col-md-12">
                    <a href="{% url 'homepage:homepage' %}"><img src="{% static 'panah.png' %}" width="30" height="30" style="margin-top: 200px;"></a> 
                  </div>
                </div>
          </div>
    </body>
</html>

homepage/templates/Hobi.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <title>
            Hobinya Dafiq?
        </title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:black;">
            <a class="navbar-brand" href="#">Dafiq Achmad - 1906308343</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'homepage:homepage' %}">Halaman Utama</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'homepage:riwayat' %}">Pendidikan</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'homepage:hobi' %}">Hobi & Ketertarikan<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:pengalaman' %}">Pengalaman</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:karya' %}">Karya</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:contact' %}">Hubungi Saya</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:matkulpage' %}">Form Jadwal Kuliah</a>
                  </li>
                  <li class="nav item">
                    <a class="nav-link" href="{% url 'homepage:kegiatan' %}">Form Kegiatan</a>
                  </li>
                  <li class="nav item">
                    <a class="nav-link" href="{% url 'homepage:prestasi' %}">Prestasi & Kepanitiaan</a>
                  </li>
                  <li class="nav item">
                    <a class="nav-link" href="{% url 'homepage:caribuku' %}">Cari Buku</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="https://dafiq.herokuapp.com/">Story 1</a>
                  </li>
              </ul>
            </div>
          </nav>
          <h1 style="text-align: center; margin-top: 50px;">Hobi & Ketertarikan Saya</h1>
          <section class="gallery-block cards-gallery">
            <div class="container">
                <div class="heading">
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="card border-0 transform-on-hover">
                            <img src="{% static 'kumpul.jpg' %}"" class="card-img-top" height=auto width=auto>
                            <div class="card-body">
                                <h6 style="color: dimgrey;">Nongkrong</h6>
                                <p class="text-muted card-text">Nongkrong telah menjadi passion saya. Saya bisa nongkrong dengan siapa saja asal saling terbuka.</p>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-sm-4">
                        <div class="card border-0 transform-on-hover">
                            <img src="{% static 'setup.jpg' %}" class="card-img-top" width=auto height=auto>
                            <div class="card-body">
                                <h6 style="color: dimgrey;">Produksi Musik</h6>
                                <p class="text-muted card-text">Saya sangat tertarik dengan dunia produksi musik. Saya telah memulai membuat beberapa musik yang sudah rilis di store.</p>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-sm-4">
                        <div class="card border-0 transform-on-hover">
                            <img src="{% static 'gaming.jpg' %}" class="card-img-top" width=auto height=465>
                            <div class="card-body">
                                <h6 style="color: dimgrey;">Gaming</h6>
                                <p class="text-muted card-text">Saya senang bermain game. Namun saya mudah bosan dalam bermain game.</p>
                            </div>
                        </div>
                    </div>
                </div><br />
                <div class="container">
                    <a href="{% url 'homepage:pengalaman' %}"><button class="btn">Pengalaman Saya</button></a>
                  </div>
    </body>
</html>

homepage/templates/Matakuliah.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
      <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <title>
            Form Schedule
        </title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:black;">
            <a class="navbar-brand" href="#">Dafiq Achmad - 1906308343</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'homepage:homepage' %}">Halaman Utama</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'homepage:riwayat' %}">Pendidikan</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'homepage:hobi' %}">Hobi & Ketertarikan</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:pengalaman' %}">Pengalaman</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:karya' %}">Karya</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:contact' %}">Hubungi Saya</a>
                </li>
                <li class="nav item">
                  <a class="nav-link active" href="{% url 'homepage:matkulpage' %}">Form Jadwal Kuliah<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav item">
                  <a class="nav-link" href="{% url 'homepage:kegiatan' %}">Form Kegiatan</a>
                </li>
                <li class="nav item">
                  <a class="nav-link" href="{% url 'homepage:prestasi' %}">Prestasi & Kepanitiaan</a>
                </li>
                <li class="nav item">
                  <a class="nav-link" href="{% url 'homepage:caribuku' %}">Cari Buku</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="https://dafiq.herokuapp.com/">Story 1</a>
                </li>
              </ul>
            </div>
          </nav>
        <h1 style="text-align: center; margin-top: 50px; margin-bottom: 50px;">Form Mata Kuliah</h1>
		  <div class="container">
            <div class="row">
                <div class="col-md-12" style="text-align: left;">
                    <form action='' method="POST">
                        {% csrf_token %}
                        {{ form }}
                        <div class="centre-items" style="margin-top: 50px; text-align: center;">
                            <input type="submit" class="btn btn-primary" value="Add Form" style="margin-bottom: 50px;">
                        </div>
                    </form>
                </div>
                <div class="col" id="tulisan">
                    <table class="table">
                        <thead>
                            <tr>
                            <th scope="col">Mata Kuliah</th>
                            <th scope="col">Dosen</th>
                            <th scope="col">SKS</th>
                            <th scope="col">Tahun</th>
                            <th scope="col">Kelas</th>
                            <th scope="col">Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for mat in matakuliah %}
                                <tr>
                                <th scope="row">{{mat.mata_kuliah}}</th>
                                <td>{{mat.dosen}}</td>
                                <td>{{mat.sks}}</td>
                                <td>{{mat.tahun}}</td>
                                <td>{{mat.kelas}}</td>
                                <td><a href="{% url 'homepage:delete' pk=mat.pk %}"><button class="btn btn-icon btn-danger"><i class="fa fa-trash"></i></button></a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
        </div>

	</body>
</html>

homepage/templates/register.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/ui-darkness/jquery-ui.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>     
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>    
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'story9.css' %}">
      <script src="{% static 'js/story8.js' %}"></script>

        <title>
            Daftar
        </title>
    </head>
    <body>
      
      <div class="container">
        <h1 class='judul'>Registration Form</h1>
        <form method="POST">
            {% csrf_token %}
            
                <div class="form">
                    Username: {{form.username}}
                </div>
                <div class="form">
                    Email: {{form.email}} 
                </div>
                <div class="form">
                    Password: {{form.password1}}
                </div>
                <div class="form">
                    Re-enter Password: {{form.password2}}
                </div>
                <br/>
                <div class="tombol">
                    <input type="submit" class="btn btn-primary tombol" value="Register" id="submit">
                </div>
            
        </form>
        </div>
     
    </body>
    
</html>